### PR TITLE
CSS shorthand properties expansion

### LINKED ISSUE #3: Shorthand props to longform question
Hi. I was wondering if adding a new feature of auto-rewriting shorthand properties into long-form would make sense for this project? Here's a example:

input:

```
   padding: 0
```

output object:

```
{
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
}
```

Here's why. There's this bug here in https://github.com/FormidableLabs/radium/issues/95 which leads further to this discussion https://github.com/facebook/react/issues/6348. The problem (as I understand it) is that mixing short-hand and long-form props in one object leads to weird results. In recent versions of Radium you get a warning when you mix them. Solution for now is to avoid short-hand props where there are conflicts but if `react-styling` could expand those then that would be a nice solution for the problem maybe?

### PR DESCRIPTION
**Pull request by pwlmc**
@halt-hammerzeit 
Shorthand props expansion using`style-builder`.
Closes #3.

### CODE REVIEW

**Comment by halt-hammerzeit** [comment]
Thanks for the PR.
I'm merging it in.
Though looking at `border` expansion I think a lot of people aren't gonna be happy about that being the default behaviour (think playing with styles in the browser) so I think we're gonna introduce an expansion flag.
I guess it's gonna be `import styler from 'react-styling/expanded'`

**Comment by pwlmaciejewski** [comment]
@halt-hammerzeit Np. Same here about `border` expansion. It can mess up existing styles as well and  I  guess some kind of flag would be a nice touch. Maybe some global option? Like: 
```
import styler from `react-styling`
styler.expandShorthandProps = false
```
Not the cleanest solution but should do the trick.

**Comment by halt-hammerzeit** [comment]
Merged the first part of your PR.
https://github.com/halt-hammerzeit/react-styling/commit/23e255a2603406199ccfeb28f47e994636002cc4
The latest version should expand now.


### Shorthand style property expansion

[A request was made](https://github.com/halt-hammerzeit/react-styling/issues/3) to [add](https://github.com/halt-hammerzeit/react-styling/pull/4) shorthand style property expansion feature to this library. The motivation is that when writing a CSS rule like `border: 1px solid red` in a base class and then overriding it with `border-color: blue` in some modifier class (like `:hover`) it's all merged correctly both when `:hover` is added and when `:hover` is removed. In React though, style rule update algorythm is not nearly that straightforward and bulletproof, and is in fact [a very basic one](https://github.com/facebook/react/issues/5397) which results in React not handling shorhand CSS property updates correctly. In these cases a special flavour of `react-styling` can be used:

```js
import styler from 'react-styling/expanded'

styler `
  margin: 10px
  border: 1px solid red
`
```

Which results in the following style object

```js
{
  marginTop    : '10px',
  marginBottom : '10px',
  marginLeft   : '10px',
  marginRight  : '10px',

  borderTopWidth: '1px',
  borderTopStyle: 'solid',
  borderTopColor: 'red',
  // etc
}
```

**Comment by pwlmaciejewski** [comment]
Thanks! 👍

**Pull request closed without merging**
